[package]
name = "hangul-fun"
version = "0.1.0"
edition = "2024"
authors = ["Atul Varma <varmaa@gmail.com>"]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
crossterm = "0.29.0"
nom = "8.0.0"
rand = "0.8"
rodio = "0.20.1"
